# Import Library

In [1]:
from sklearn.model_selection import train_test_split
import numpy as np

# Create dataset

In [2]:
X, y = np.arange(50).reshape(10,5), np.arange(10)

In [3]:
print('X: shape'+ str(X.shape))
print(X)
print('y: shape'+ str(y.shape))
print(y)

X: shape(10, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
y: shape(10,)
[0 1 2 3 4 5 6 7 8 9]


# Training & Testing Data Split

In [4]:
# trying to tune shuffle and random_state
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state= 42, shuffle=False)

In [5]:
X_train

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [6]:
y_train

array([0, 1, 2, 3, 4, 5])