# Cross Validation with KFold

In [1]:
import numpy as np

#試著print出X_train, X_test，並將shuffle改成True看看結果如何變化。

In [2]:
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array([1, 2, 3, 4, 5])
kf = KFold(n_splits=5, random_state=None, shuffle=False)
for train_index, val_index in kf.split(X):
    X_train, X_val = X[train_index], X[val_index]
    y_train, y_val = y[train_index], y[val_index]
    print("TRAIN index:", train_index, "Validation index:", val_index)

TRAIN index: [1 2 3 4] Validation index: [0]
TRAIN index: [0 2 3 4] Validation index: [1]
TRAIN index: [0 1 3 4] Validation index: [2]
TRAIN index: [0 1 2 4] Validation index: [3]
TRAIN index: [0 1 2 3] Validation index: [4]


# Print Training and Validation data

In [3]:
i =1
for train_index, val_index in kf.split(X):
    X_train, X_val = X[train_index], X[val_index]
    y_train, y_val = y[train_index], y[val_index]
    print('Cross Validation%d=============='%i,'\n' 
          "TRAIN data:",'\n', X_train,'\n'
          ,"Validation data:", X_val)
    i+=1

Cross Validation1============== 
TRAIN data: 
 [[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 
 Validation data: [[1 2]]
Cross Validation2============== 
TRAIN data: 
 [[ 1  2]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 
 Validation data: [[3 4]]
Cross Validation3============== 
TRAIN data: 
 [[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]] 
 Validation data: [[5 6]]
Cross Validation4============== 
TRAIN data: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 9 10]] 
 Validation data: [[7 8]]
Cross Validation5============== 
TRAIN data: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 
 Validation data: [[ 9 10]]
